# Uncomment the following lines to define your default indexer and rpc urls
indexer_url      = "https://indexer.housefire.tududes.com/api/v1/pos/validator/all"
rpc_url          = "https://rpc.housefire.tududes.com"
masp_indexer_url = "https://masp.housefire.tududes.com/api/v1/height"
localnet_enabled = false
